name: Run Tests in my project every push on GitHub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup_node@v3
      with:
        node-version: 14
    - run: npm install
    - run: npm test

    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3